CREATE TABLE Roles (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    RoleName VARCHAR(50) NOT NULL
);

CREATE TABLE Users (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    FirstName VARCHAR(50) NOT NULL,
    UserName VARCHAR(50) NOT NULL UNIQUE,
    LastName VARCHAR(50) NOT NULL,
    Gender INTEGER,
    Email VARCHAR(255),
    PasswordHash VARCHAR(512) NOT NULL,
    DOB DATETIME,
    PhoneNo VARCHAR(10),
    RoleId INTEGER NOT NULL,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE Addresses (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(50) NOT NULL,
    MobileNo VARCHAR(10) NOT NULL,
    City VARCHAR(50) NOT NULL,
    State VARCHAR(200) NOT NULL,
    Pincode VARCHAR(6) NOT NULL,
    StreetAddress VARCHAR(100) NOT NULL,
    Landmark VARCHAR(100) NOT NULL,
    UserId INTEGER NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Categories (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE Brands (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(20) NOT NULL
);

CREATE TABLE Products (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(100) NOT NULL,
    Price FLOAT NOT NULL,
    Description VARCHAR(2000) NOT NULL,
    StockAvailable INTEGER NOT NULL,
    ImagePath VARCHAR(50) NOT NULL,
    CategoryId INTEGER NOT NULL,
    BrandId INTEGER NOT NULL,
    FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
    FOREIGN KEY (BrandId) REFERENCES Brands(Id)
);

CREATE TABLE Orders (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    UserId INTEGER NOT NULL,
    TotalAmount FLOAT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    Status VARCHAR(10) NOT NULL,
    AddressId INTEGER NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
);

CREATE TABLE OrderDetails (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    OrderId INTEGER NOT NULL,
    ProductId INTEGER NOT NULL,
    Quantity INTEGER NOT NULL,
    Price FLOAT NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES Orders(Id),
    FOREIGN KEY (ProductId) REFERENCES Products(Id)
);

CREATE TABLE Carts (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    UserId INTEGER NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE CartDetails (
    Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
    CartId INTEGER NOT NULL,
    ProductId INTEGER NOT NULL,
    Quantity INTEGER NOT NULL,
    FOREIGN KEY (CartId) REFERENCES Carts(Id),
    FOREIGN KEY (ProductId) REFERENCES Products(Id)
);